spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          google:
            issuer-uri: https://accounts.google.com
        registration:
          google:
            client-id: .apps.googleusercontent.com
            client-secret:
            scope: openid,profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  cloud:
    gateway:
      default-filters:
        - OIDCTokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: movie-service-route
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: serie-service-route
          uri: lb://serie-service
          predicates:
            - Path=/series/**
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
    instance:
      preferIpAddress: true

