spring:
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
  application:
    name: movie-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql-movie:3306/movie_database
    username: root
    password: root
  sql:
    init:
      mode: always
      dataLocations: classpath:/movie-service.sql
  jpa:
    deferDatasourceInitialization: true
    show-sql: true
    hibernate:
      ddlAuto: create-drop
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

queue:
  movie:
    name: MovieQueue

server:
  port: 8061

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    preferIpAddress: true